[build-system]
# >= 61: configuration in "pyproject.toml"
requires = ["setuptools >= 61"]
build-backend = "setuptools.build_meta"


[project]
name            = "mailqueue-runner"
readme          = "README.md"
license         = {text = "MIT and Python"}
requires-python = ">= 3.8"
dynamic         = ["version"]

authors = [
    {name = "Felix Schwarz", email = "felix.schwarz@oss.schwarz.eu"},
]

dependencies = [
    "boltons",
    "docopt",
    "portalocker",
]

[project.optional-dependencies]
plugins = [
    # >= 0.8.0: switch to plain importlib instead of pkg_resources
    "PuzzlePluginSystem >= 0.8.0",
]
colors = [
    "colorama",
]
# "testutils" provides helpers to simplify testing (also usable by 3rd party code)
testutils = [
    # >= 0.8: SMTPCommandParser
    "pymta >= 0.8",
    "schwarzlog",
]
testing = [
    "mailqueue-runner[plugins,testutils]",
    "dotmap",
    "time-machine; implementation_name != 'pypy'",
    "pytest",
    "testfixtures",
]

[project.urls]
Homepage = "https://github.com/FelixSchwarz/mailqueue-runner"

[project.scripts]
mq-mail      = "schwarz.mailqueue.cli:mq_mail_main"
mq-run       = "schwarz.mailqueue.cli:one_shot_queue_run_main"
mq-send-test = "schwarz.mailqueue.cli:send_test_message_main"
mq-sendmail  = "schwarz.mailqueue.cli:mq_sendmail_main"


[tool.setuptools.dynamic]
version = {file = "VERSION.txt"}

[tool.setuptools.packages.find]
include = ["schwarz*"]


[tool.ruff]
line-length = 100
src = ["schwarz", "tests"]

ignore = [
    # F405 "… may be undefined, or defined from star imports: …"
    #    Sometimes star imports are perfectly fine IMHO.
    "F403",
    "F405",
    # E731: "Do not assign a `lambda` expression, use a `def`"
    #    I think assigning to lambda expressions is ok.
    "E731",
]

select = [
    # Pyflakes
    "F",
    # Pycodestyle
    "E",
    "W",
    # isort
    "I001",

    # Special rule code to enforce that your noqa directives are "valid", in that
    # the violations they say they ignore are actually being triggered on that line
    # (and thus suppressed).
    # replaces basically "yesqa"
    "RUF100",
]

[tool.ruff.isort]
lines-after-imports = 2
known-first-party = ["schwarz.mailqueue"]
combine-as-imports = true
