#!/usr/bin/env python
# -*- coding: utf-8 -*-
# SPDX-License-Identifier: MIT

from __future__ import absolute_import, print_function, unicode_literals

from schwarz.mailqueue.cli import one_shot_queue_run_main


one_shot_queue_run_main()
