name: run tests

on:
  push:
    branches:
    - main
    - ci
  pull_request:
    branches:
    - main


env:
  # query OSV for known malware before syncing
  UV_MALWARE_CHECK: "1"


jobs:
  tests-cpython:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9, "3.10", "3.11", "3.12", "3.13", "latest"]
    container:
      image: python:${{ matrix.python-version }}

    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v10.1.0
      with:
        version: "latest-known"

    - name: Install dependencies and run tests
      run: |
        uv venv --python python venv-test
        . venv-test/bin/activate
        uv pip install -e '.[testing]'
        uv run --active --no-project pytest


  tests_pypy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pypy-version: ["3.10", "3.11", "latest"]
    container:
        image: pypy:${{ matrix.pypy-version }}

    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v10.1.0
      with:
        version: "latest-known"

    - name: Install dependencies and run tests
      run: |
        uv venv --python python venv-test
        . venv-test/bin/activate
        uv pip install -e '.[testing]'
        uv run --active --no-project pytest


  # --- testing on Windows ------------------------------------------
  tests-windows:
    runs-on: windows-latest
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v10.1.0
      with:
        version: "latest-known"
        python-version: ${{ matrix.python-version }}
        activate-environment: true

    - name: Install dependencies
      run: |
        uv pip install -e '.[testing]'

    - name: Run test suite
      run: |
        uv run --active --no-project pytest
